"""Python entity API for IoTAuth."""

from .config import (
    AuthInfo,
    EntityConfig,
    EntityInfo,
    SessionConfig,
    TargetServer,
    load_config,
)
from .context import IoTAuthContext
from .credentials import load_auth_public_key, load_entity_private_key
from .client import SecureClient
from .auth_service import distribution_key_is_expired, request_session_keys
from .protocol import (
    AUTH_ID_SIZE,
    NONCE_SIZE,
    AuthAlertPayload,
    AuthHelloPayload,
    IoTSPFrame,
    MessageType,
    SessionKeyRequestPayload,
    SessionKeyResponsePayload,
    message_type_from_byte,
    parse_auth_alert_payload,
    parse_auth_hello_payload,
    parse_buffered_string,
    parse_distribution_key_record,
    parse_frame,
    parse_session_key_record,
    parse_session_key_response_payload,
    serialize_buffered_string,
    serialize_frame,
    serialize_session_key_request_payload,
)
from .exceptions import (
    AuthConnectionError,
    AuthProtocolError,
    ConfigError,
    CredentialError,
    ExpiredKeyError,
    InvalidSequenceNumberError,
    IoTAuthError,
    KeyCacheError,
    MessageIntegrityError,
    SerializationError,
    SecureChannelClosed,
    SecureHandshakeError,
    UnsupportedCryptoError,
)
from .handshake import (
    HANDSHAKE_DH_PARAM_PRESENT,
    HANDSHAKE_FIXED_SIZE,
    HANDSHAKE_NONCE_PRESENT,
    HANDSHAKE_REPLY_NONCE_PRESENT,
    HandshakePayload,
    build_handshake_1,
    parse_handshake_1_key_id,
    parse_handshake_payload,
    serialize_handshake_payload,
    verify_handshake_1_and_build_handshake_2,
    verify_handshake_2_and_build_handshake_3,
    verify_handshake_3,
)
from .crypto import (
    decrypt_request_with_distribution_key,
    encrypt_and_sign_for_auth,
    encrypt_request_with_distribution_key,
    private_decrypt,
    public_encrypt,
    sign_sha256,
    symmetric_decrypt_authenticate,
    symmetric_encrypt_authenticate,
    verify_and_decrypt_from_auth,
    verify_sha256,
)
from .keys import DistributionKey, SessionKey, SessionKeyCache
from .serialization import (
    decode_uint_be,
    decode_varint,
    encode_uint_be,
    encode_varint,
)
from .secure_channel import (
    SecureChannel,
    accept_secure,
    connect_secure,
    session_key_is_expired,
)
from .server import SecureServer
from .transports import recv_frame, send_frame

__all__ = [
    "AUTH_ID_SIZE",
    "accept_secure",
    "AuthConnectionError",
    "AuthAlertPayload",
    "AuthHelloPayload",
    "AuthProtocolError",
    "AuthInfo",
    "ConfigError",
    "CredentialError",
    "decode_uint_be",
    "decode_varint",
    "decrypt_request_with_distribution_key",
    "DistributionKey",
    "distribution_key_is_expired",
    "encrypt_and_sign_for_auth",
    "encrypt_request_with_distribution_key",
    "encode_uint_be",
    "encode_varint",
    "EntityConfig",
    "EntityInfo",
    "ExpiredKeyError",
    "InvalidSequenceNumberError",
    "HANDSHAKE_DH_PARAM_PRESENT",
    "HANDSHAKE_FIXED_SIZE",
    "HANDSHAKE_NONCE_PRESENT",
    "HANDSHAKE_REPLY_NONCE_PRESENT",
    "HandshakePayload",
    "build_handshake_1",
    "connect_secure",
    "IoTAuthContext",
    "IoTAuthError",
    "IoTSPFrame",
    "KeyCacheError",
    "MessageIntegrityError",
    "MessageType",
    "message_type_from_byte",
    "NONCE_SIZE",
    "parse_auth_alert_payload",
    "parse_auth_hello_payload",
    "parse_buffered_string",
    "parse_distribution_key_record",
    "parse_frame",
    "parse_handshake_1_key_id",
    "parse_handshake_payload",
    "parse_session_key_record",
    "parse_session_key_response_payload",
    "private_decrypt",
    "public_encrypt",
    "SerializationError",
    "serialize_buffered_string",
    "serialize_frame",
    "serialize_handshake_payload",
    "serialize_session_key_request_payload",
    "SecureChannel",
    "SecureChannelClosed",
    "SecureClient",
    "SecureHandshakeError",
    "SecureServer",
    "SessionConfig",
    "SessionKey",
    "SessionKeyCache",
    "session_key_is_expired",
    "SessionKeyRequestPayload",
    "SessionKeyResponsePayload",
    "recv_frame",
    "request_session_keys",
    "send_frame",
    "sign_sha256",
    "symmetric_decrypt_authenticate",
    "symmetric_encrypt_authenticate",
    "TargetServer",
    "UnsupportedCryptoError",
    "verify_and_decrypt_from_auth",
    "verify_handshake_1_and_build_handshake_2",
    "verify_handshake_2_and_build_handshake_3",
    "verify_handshake_3",
    "verify_sha256",
    "load_auth_public_key",
    "load_config",
    "load_entity_private_key",
]
