"""Python entity API for IoTAuth."""

from .config import (
    AuthInfo,
    EntityConfig,
    EntityInfo,
    SessionConfig,
    TargetServer,
    load_config,
)
from .context import IoTAuthContext
from .auth_service import distribution_key_is_expired, request_session_keys
from .auth_messages import (
    AUTH_ID_SIZE,
    NONCE_SIZE,
    AuthAlertPayload,
    AuthHelloPayload,
    SessionKeyRequestPayload,
    SessionKeyResponsePayload,
    parse_auth_alert_payload,
    parse_auth_hello_payload,
    parse_buffered_string,
    parse_distribution_key_record,
    parse_session_key_record,
    parse_session_key_response_payload,
    serialize_buffered_string,
    serialize_session_key_request_payload,
)
from .exceptions import (
    AuthConnectionError,
    AuthProtocolError,
    ConfigError,
    CredentialError,
    IoTAuthError,
    KeyCacheError,
    MessageIntegrityError,
    SerializationError,
    UnsupportedCryptoError,
)
from .crypto import (
    decrypt_request_with_distribution_key,
    encrypt_and_sign_for_auth,
    encrypt_request_with_distribution_key,
    private_decrypt,
    public_encrypt,
    sign_sha256,
    symmetric_decrypt_authenticate,
    symmetric_encrypt_authenticate,
    verify_and_decrypt_from_auth,
    verify_sha256,
)
from .keys import DistributionKey, SessionKey, SessionKeyCache
from .messages import IoTSPFrame, MessageType, message_type_from_byte
from .serialization import (
    decode_uint_be,
    decode_varint,
    encode_uint_be,
    encode_varint,
    parse_frame,
    serialize_frame,
)
from .transports.tcp import recv_frame, send_frame

__all__ = [
    "AUTH_ID_SIZE",
    "AuthConnectionError",
    "AuthAlertPayload",
    "AuthHelloPayload",
    "AuthProtocolError",
    "AuthInfo",
    "ConfigError",
    "CredentialError",
    "decode_uint_be",
    "decode_varint",
    "decrypt_request_with_distribution_key",
    "DistributionKey",
    "distribution_key_is_expired",
    "encrypt_and_sign_for_auth",
    "encrypt_request_with_distribution_key",
    "encode_uint_be",
    "encode_varint",
    "EntityConfig",
    "EntityInfo",
    "IoTAuthContext",
    "IoTAuthError",
    "IoTSPFrame",
    "KeyCacheError",
    "MessageIntegrityError",
    "MessageType",
    "message_type_from_byte",
    "NONCE_SIZE",
    "parse_auth_alert_payload",
    "parse_auth_hello_payload",
    "parse_buffered_string",
    "parse_distribution_key_record",
    "parse_frame",
    "parse_session_key_record",
    "parse_session_key_response_payload",
    "private_decrypt",
    "public_encrypt",
    "SerializationError",
    "serialize_buffered_string",
    "serialize_frame",
    "serialize_session_key_request_payload",
    "SessionConfig",
    "SessionKey",
    "SessionKeyCache",
    "SessionKeyRequestPayload",
    "SessionKeyResponsePayload",
    "recv_frame",
    "request_session_keys",
    "send_frame",
    "sign_sha256",
    "symmetric_decrypt_authenticate",
    "symmetric_encrypt_authenticate",
    "TargetServer",
    "UnsupportedCryptoError",
    "verify_and_decrypt_from_auth",
    "verify_sha256",
    "load_config",
]
